INSERT INTO _CEL_P2P_ACTIVITIES(
  "_CASE_KEY" 
  , "ACTIVITY_EN" 
  , "EVENTTIME" 
, "SORTING") 
SELECT 
"EKPO"."MANDT" || "EKPO"."EBELN" || "EKPO"."EBELP" AS "_CASE_KEY"
, 'Change Price' AS "ACTIVITY_EN"
, CAST("CDHDR"."UDATE" AS DATE) + CAST("CDHDR"."UTIME" AS TIME) AS "EVENTTIME"
,30 AS "SORTING"
FROM 
"EKPO" JOIN "EKKO"
ON "EKPO"."MANDT" = "EKKO"."MANDT"
AND "EKPO"."EBELN" = "EKKO"."EBELN"
JOIN "CDPOS" 
ON "CDPOS"."TABNAME"= 'EKPO'
AND "CDPOS"."TABKEY" = "EKPO"."MANDT" || "EKPO"."EBELN" || "EKPO"."EBELP"
JOIN "CDHDR" 
ON "CDHDR"."MANDANT" = "CDPOS"."MANDANT" 
AND "CDPOS"."CHANGENR" = "CDHDR"."CHANGENR"
WHERE "EKKO"."BSTYP" = 'F' 
AND "CDPOS"."FNAME" = 'MENGE'; 
